import { SLICE_KEY } from "./constant";

export const ACTION_TYPES = {
  SIGNUP: `${SLICE_KEY}/SIGNUP`,
  LOGIN: `${SLICE_KEY}/LOGIN`,
  REFRESH_ACCESS_TOKEN: `${SLICE_KEY}/REFRESH_ACCESS_TOKEN`,
  REFRESH_PASSWORD: `${SLICE_KEY}/REFRESH_PASSWORD`,
};
