import { SLICE_KEY } from "./constant";

export const ACTION_TYPES = {
  SIGNUP: `${SLICE_KEY}/SIGNUP`,
  LOGIN: `${SLICE_KEY}/LOGIN`,
  REFRESH_ACCESS_TOKEN: `${SLICE_KEY}/REFRESH_ACCESS_TOKEN`,
  FORGET_PASSWORD: `${SLICE_KEY}/FORGET_PASSWORD`,
  RESET_PASSWORD: `${SLICE_KEY}/RESET_PASSWORD`,
  LOGOUT: `${SLICE_KEY}/LOGOUT`,
};
