import { SLICE_KEY } from "./constant";

export const ACTION_TYPES = {
  FETCH_USERS: `${SLICE_KEY}/FETCH_USERS`,
  CREATE_COURSE: `${SLICE_KEY}/CREATE_COURSE`,
  DELETE_COURSE: `${SLICE_KEY}/DELETE_COURSE`,
  FETCH_BATCHES: `${SLICE_KEY}/FETCH_BATCHES`,
};
