import { SLICE_KEY } from "./constant";

export const ACTION_TYPES = {
  FETCH_TRANSACTIONS: `${SLICE_KEY}/FETCH_TRANSACTIONS`,
  FETCH_COURSES: `${SLICE_KEY}/FETCH_COURSES`,
  FETCH_COURSE_DETAILS: `${SLICE_KEY}/FETCH_COURSE_DETAILS`,
  FETCH_DEPARTMENTS: `${SLICE_KEY}/FETCH_DEPARTMENTS`,
  ADD_BOOK: `${SLICE_KEY}/ADD_BOOK`,
  FETCH_BOOKS: `${SLICE_KEY}/FETCH_BOOKS`,
  BORROW_BOOK: `${SLICE_KEY}/BORROW_BOOK`,
  DOWNLOAD_BOOKS_EXCEL: `${SLICE_KEY}/DOWNLOAD_BOOKS_EXCEL`,
};
